### ISSUE TITLE
No ENABLE_RESET key in the server.default.dat file.

### ISSUE THREAD

**Issue by carlostighe** [andrewcottam/marxan-server#3]
`ENABLE_RESET = _getDictValue(serverData,'ENABLE_RESET')`  

There is no `ENABLE_RESET` key in the server.dat file.

**Comment by andrewcottam** [comment]
Thanks a lot Carlos! I really appreciate your input. Do you have an interest in the project or Marxan?

**Comment by carlostighe** [comment]
Hey Andrew,

I have an interest in the project. On a project where the idea was to implement marxan on top of other functions and came across this project which seems to satisfy many of the requirements. 

Trying to put it all together. Youve done some serious work on this.

**Comment by andrewcottam** [comment]
Yes its taken me a while - I've been working on it with The Nature
Conservancy. I based at the Joint Research Centre in Italy. You're very
welcome to contribute to the project if you would like to.

Best wishes,
Andrew

**Comment by andrewcottam** [comment]
Well actually - you already have :)
