### ISSUE TITLE
_getPlanningUnitGrids returning each pu grid 3 times.

### ISSUE THREAD

**Issue by carlostighe** [andrewcottam/marxan-server#6]
Hey Andrew, 
Happy New Year. 

https://github.com/marxanweb/marxan-server/blob/ecbe51fca1e8d0f9fa8d83fced0e2d3f79c89d17/marxan-server.py#L944

Did a fresh pull and setup recently and the `_getPlanningUnitGrids` function, reffed above, is returning three of each planning unit grid. 

To fix locally I did a `"SELECT DISTINCT (feature_class_name)` and removed the order by on the query but just wondering if this was an issue or is it just affecting my install?

**Comment by carlostighe** [comment]
changed query to 

`return await pg.execute("SELECT DISTINCT (alias), feature_class_name, description ,to_char(creation_date, 'DD/MM/YY HH24:MI:SS')::text AS creation_date ,country_id ,aoi_id,domain,_area,ST_AsText(envelope) envelope, pu.source, original_n country, created_by,tilesetid, planning_unit_count FROM marxan.metadata_planning_units pu LEFT OUTER JOIN marxan.gaul_2015_simplified_1km ON id_country = country_id order by alias;", returnFormat="Dict")`  

Im not hugely familiar with postgres so I dont know if this will cause issues but it seems to be working.

**Comment by andrewcottam** [comment]
Thanks Carlos - adding DISTINCT is a good idea as it will remove duplicates if there are no matching records in the country table (gaul_2015_simplified). Can you put it in as a pull request?
